### ISSUE TITLE
Unused '$ret' variable in batch_example_update_1100()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/examples#12]
The `batch_example_update_1100()` function starts with `$ret = array();` but this variable is never mentioned/used again. Additionally, it's not very well named. We should remove it.

https://github.com/backdrop-contrib/examples/blob/1.x-1.x/batch_example/batch_example.install#L28

**Comment by avpaderno** [comment]
I verified the variable is effectively not used by the update hook and provided a PR to removed it.
