### ISSUE TITLE
In Simpletest example description, use the Testing Framework URL in docs

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/examples#17]
Currently the module description for Simpletest Example says:

> An example of simpletest tests to accompany the tutorial at https://api.backdropcms.org/node/41659.

We should use the current docs.b.org URL for that node, which is:

https://docs.backdropcms.org/documentation/testing-framework

Also, it's not really a "tutorial", so better to say:

An example of simpletest tests to accompany the documentation at https://docs.backdropcms.org/documentation/testing-framework.

**Comment by avpaderno** [comment]
The same link and similar description is used in `_simpletest_example_explanation()` too. I corrected that in a follow-up.
