### ISSUE TITLE
Move test files into tests subfolders

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/examples#19]
Backdrop standard for organization of test files is to put them all into the `tests` sub-directory. Since the example modules should show the best practices, they should follow this pattern. (Currently, test files are placed on the module root directory.)

**Comment by avpaderno** [comment]
This should also be done for the tests provided by other modules in this project. As examples of good practice, they should all follow the same directory schema, or it would seem that, for example, putting the tests in a *tests* directory is not a good practice.

**Comment by avpaderno** [comment]
I am postponing this because merging other PRs creates merging conflicts with the PR for this issue. I will provide a PR when I can merge it as first.
