### ISSUE TITLE
No blank line between <?php and first docblock

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/examples#21]
Backdrop coding standards call for no blank line between the `<?php` and the first docblock. Examples should follow this standard.

**Comment by avpaderno** [comment]
Yes, [Indenting and Whitespace](https://docs.backdropcms.org/php-standards#indenting) clearly states that.

> The `/** @file */` docblock at the beginning of a PHP file should not be preceded by a blank line, but should be followed by a blank line.

The example code is also clear.

```php
<?php
/**
 * @file
 * Foo file does bar.
 */

/**
 * Implements hook_baz().
 */
```
