### ISSUE TITLE
image_example_colorize_effect() does not use the correct placeholder

### ISSUE THREAD

**Issue by avpaderno** [backdrop-contrib/examples#25]
[`image_example_colorize_effect()`](https://docs.backdropcms.org/api/backdrop/modules%21examples%21image_example%21image_example.module/function/image_example_colorize_effect/1) logs an error message using the following code.

```php
if (!function_exists('imagefilter')) {
  watchdog('image', 'The image %image could not be colorized because the imagefilter() function is not available in this PHP installation.', array('%file' => $image->source));
  return FALSE;
}
```

The used placeholder is `%image` but then the `'%file'` index is provided in the array passed as second argument for  `watchdog()`. The array index should be `'%image'`, or the logged error will literally be *The image %image could not be colorized because the imagefilter() function is not available in this PHP installation.* where the placeholder is not replaced.

**Comment by argiepiano** [comment]
Thanks for providing the PR, @kiamlaluno . 

It's good practice to link PRs to the main issues by adding the magic words `Fixes #XXX` in the PR description. It's also a good idea to include a comment here pointing at that PR, as in:

PR #26
