### ISSUE TITLE
Offering to be maintainer

### ISSUE THREAD

**Issue by avpaderno** [backdrop-contrib/examples#27]
I am offering to be maintainer, to help fixing coding standards, issues, and typos. I know the project functions are listed on docs.backdropcms.org and that attention must be taken to not introduce new typos or (worse) bugs in the code.

PR #28

**Comment by herbdool** [comment]
According to https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Offering.20to.20maintain.20the.20Examples.20project/near/377360458 @docwilmot would be happy to add you as a maintainer @kiamlaluno.

**Comment by avpaderno** [comment]
@herbdool That is why I created this issue and provided a PR. 😉
