### ISSUE TITLE
Remove the "example_empty" block

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/examples#5]
In Backdrop you can no longer specify a default region for blocks in `hook_block_info()`. This appears to have been the primary purpose of the `example_empty` block from the code comment above it:

```
  // This sample shows how to provide default settings. In this case we'll
  // enable the block in the first sidebar and make it visible only on
  // 'node/*' pages. See the hook_block_info() documentation for these.
  $blocks['example_empty'] = array(
    'info' => t('Example: empty block'),
    'description' => 'This is an empty block.',
  );
```

Seems like we should just remove this entire example because it doesn't seem to provide a lot of value any more.

**Comment by docwilmot** [comment]
Thanks for your review. agreed re empty block, will delete.

**Comment by docwilmot** [comment]
Removed empty block and added a class-defined block.
Closing, thanks.
