### ISSUE TITLE
Remove any link to DrupalCon sites that have been converted to a static site

### ISSUE THREAD

**Issue by avpaderno** [backdrop-contrib/examples#54]
The *theming_example.module* file contains the following link, in a comment.

```none
* @link http://sf2010.DOCUMENTATION_PENDING/conference/sessions/batch-vs-queue-api-smackdown session video. @endlink
```

That originally was a link to a DrupalCon site. That link should now be https://sf2010.drupal.org/conference/sessions/batch-vs-queue-api-smackdown.html, and since DrupalCon sites have been converted to static sites, that is the only information accessible about that session. There is no link to videos to watch; the text visible in that page does not explain the difference between Batch API and Queue API.  
I also checked the [YouTube videos published from the Drupal Association](https://www.youtube.com/@DrupalAssociation), but the older videos are from 2011.

That link needs to be removed. If there are other similar links, they should be removed.

This issue is part of #23 (third point).

**Comment by avpaderno** [comment]
There were just a link to be removed.

**Comment by argiepiano** [comment]
~~How about adding a link to the actual video from that presentation?~~

How about adding a link to the slides from that presentation?
https://www.sysarchitects.com/files/Batch_and_Queue_0.pdf

Or finding another relevant video or resource?

**Comment by avpaderno** [comment]
The slides are already linked from the *theming_example.module* file: http://www.ent.iastate.edu/it/Batch_and_Queue.pdf.
