### ISSUE TITLE
Entity example not working.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/examples#7]
I have just tried this in Backdrop 1.4.3 and have hit problems. When trying to add an entity example I got:

Fatal error: Call to undefined method stdClass::entityType() in /httpdocs/backdrop/core/modules/filter/filter.module on line 1739

The error log from /admin/structure/entity_example_basic/manage/add was:

Recoverable fatal error: Argument 1 passed to filter_entity_insert() must be an instance of EntityInterface, instance of stdClass given in filter_entity_insert() (line 1590 of /httpdocs/backdrop/core/modules/filter/filter.module).

I then tried to run the inbuilt tests but these are failing.

@docwilmot I think there must have been significant changes to entities since April 2015 when you ported this module. I tried this example module today because I am trying to get the Rules module to work and I am hitting problems with entity functions. If you can see what changes are needed here that could help me a lot. Thanks.

**Comment by docwilmot** [comment]
Thanks for the heads up Graham. Will check asap. Might need reminding.

**Comment by docwilmot** [comment]
Fixed
