### ISSUE TITLE
Official Release?

### ISSUE THREAD

**Issue by wesruv** [backdrop-contrib/examples#8]
Teaching some mentees Backdrop and told them to find the examples module, there wasn't an easy way for them to find it since there wasn't an official release.

**Comment by docwilmot** [comment]
Working on this. Been a few core changes since I last looked at it, so tests are failing all over the place.

**Comment by docwilmot** [comment]
Wasnt really sure this should be listed as an official module, since it isnt a real module as such, but released anyway. Thanks.
