### ISSUE TITLE
None of these modules include "type" in .info file

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/examples#9]
Noticing that documentation for creating a modules says to include "type = module" in the .info file, but none of the example modules have that. 

I assume that is because these are technically sub-modules. Should we:
1) Add that line to each sub-module and comment it out?
2) Add that line to each sub-module?
3) Add a note in README noting the difference between sub-modules and modules?

**Comment by docwilmot** [comment]
> I assume that is because these are technically sub-modules

More likely because Examples predate the decision to require `"type = module"`. We should do choice 2.

**Comment by stpaultim** [comment]
I'll do a PR

**Comment by stpaultim** [comment]
Here is a PR = https://github.com/backdrop-contrib/examples/pull/10

**Comment by docwilmot** [comment]
I've merged this, thanks.
